import { Geist, Geist_Mono } from "next/font/google";
import NavBar from "@/components/NavBar";
import StoreNav from "@/components/StoreNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <body>
        <div className="flex h-screen">
         
          <NavBar />
          <main className="w-full overflow-y-auto">
          {children}
          </main>
        </div>
      </body>
    </html>
  );
}
